09-usuariosdj/django-app/apps/home/urls.py
from django.urls import path

from . import views

app_name = 'home_app'


urlpatterns = [
    path(
        'panel/',
        views.HomePage.as_view(),
        name='panel'
    ),
    path(
        'mixin/',
        views.TemplatePruebaMixin.as_view(),
        name='mixin'
    ),
]

09-usuariosdj/django-app/apps/users/urls.py
from django.urls import path

from . import views


app_name = 'users_app'

urlpatterns = [
    path(
        'register/',
        views.UserRegisterView.as_view(),
        name='user-register'
    ),
    path(
        'login/',
        views.LoginUser.as_view(),
        name='user-login'
    ),
    path(
        'logout/',
        views.LogoutView.as_view(),
        name='user-logout'
    ),
    path(
        'change-password/',
        views.UpdatePasswordView.as_view(),
        name='user-change-password'
    ),
    path(
        'user-verification/<pk>',
        views.CodeVerificationView.as_view(),
        name='user-verification'
    ),
]

09-usuariosdj/django-app/core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls')),
    path('', include('apps.home.urls')),
]

09-usuariosdj/django-app/apps/home/models.py
from django.db import models

# Create your models here.

09-usuariosdj/django-app/apps/home/views.py
from datetime import datetime

from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (
    TemplateView
)


# Construir mi propio mixin
class FechaMixin(object):
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['fecha'] = datetime.now()
        return context

# vistas    
class HomePage(LoginRequiredMixin, FechaMixin, TemplateView):
    template_name = "home/index.html"
    # Atributo para el LoginRequiredMixin
    login_url = reverse_lazy('users_app:user-login')
    
class TemplatePruebaMixin(FechaMixin, TemplateView):
    template_name = 'home/mixin.html'

09-usuariosdj/django-app/templates/home/index.html
{% extends 'base.html' %}



{% block head %}
    <title>Home</title>
{% endblock head %}
    



{% block content  %}
    <h1>Panel de usuarios</h1>
    <small>{{ fecha }}</small>
    <hr>
    <h3>Bienvenidos: {{ user }}</h3>
    <ul>
        <li><a href="{% url 'users_app:user-logout' %}">Cerrar sesión</a></li>
        <li><a href="{% url 'users_app:user-change-password' %}">Actualizar datos</a></li>
    </ul>
{% endblock content  %}
    

09-usuariosdj/django-app/templates/home/mixin.html
{% extends 'base.html' %}



{% block content %}
    <h1>Prueba Mixin</h1>
    <hr>
    <p>
        {{ fecha }}
    </p>
{% endblock content %}
    